name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - testing
      - testing-ci
    types:
      - assigned
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate PR
        id: validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: false
          subjectPattern: '^[A-Z].*$'
          subjectPatternError: 'The subject of the PR title must start with a capital letter.'
        continue-on-error: true

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run tests and coverage
        run: npm test --if-present
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
